### PR TITLE
Sidebar model selection menu

### PR DESCRIPTION
**Pull request by OscarArroyoVega**
@Anteemony Please take a look at the model selection menu. The dictionary that I used is the same one that the Llama_index app uses. 
Locally, it functions.

### CODE REVIEW

**Comment by Anteemony** [comment]
Looking good. It will be nice if the model and endpoints also have the toast feature
Let me take a look locally

**Comment by OscarArroyoVega** [comment]
How does the toast feature work? Although I saw you introduce it, I am not sure how it works.

**Comment by Anteemony** [comment]
It's a very simple command. See it in the [docs](https://docs.streamlit.io/develop/api-reference/status/st.toast)

**Comment by OscarArroyoVega** [comment]
I will close the pull request, make the necessary adjustments, and submit a new PR.

**Pull request closed without merging**
