### PR TITLE
Fix/token input limit error

### LINKED ISSUE #13: Fix: Token Input Limit Error

### PR DESCRIPTION
**Pull request by Anteemony**
Fixes #13 

Passes prompt template to ConversationalRetrievalChain

### CODE REVIEW

**Comment by Anteemony** [comment]
@OscarArroyoVega Can you take a look at this?

**Review by OscarArroyoVega — APPROVED** [review]
check!

**Comment by Anteemony** [comment]
LGTM!

**Review by OscarArroyoVega — APPROVED** [review]
it looks good to me, t0 use a standard
chunk size 10000
chunk overlap 1000

**Pull request merged**
