### PR TITLE
add UX features

### LINKED ISSUE #9: Feature: Submit loading progress circle

### LINKED ISSUE #11: Feature: Clear chat history

### LINKED ISSUE #25: Feature: Field Input updated notification
Notify the user when their Key  / Endpoint has been updated using a toast message

### LINKED ISSUE #26: Feature: File Processing Status
The current file processing implementation has no feedback for the user to know what step the program is currently at.

This implementation will also help identify areas that need to be optimized / re-implemented for speedups or whatever the case may be.

### PR DESCRIPTION
**Pull request by Anteemony**
Improves user experience by adding the below features: 
This closes #26 closes #25 closes #11 and closes #9

### CODE REVIEW

**Comment by Anteemony** [comment]
@OscarArroyoVega This should improve the user experience. What do you think?

**Review by OscarArroyoVega — APPROVED** [review]

**Comment by OscarArroyoVega** [comment]
I agree that the user needed some "orientation information" after seeing the changes. A few conflicts still need to be resolved, but as you are aware from the previous version, I left them up to your interpretation.

**Comment by Anteemony** [comment]
Conflicts resolved!

**Comment by OscarArroyoVega** [comment]
Must I merge it? I mean, can you do it on your side, or does it require my approval?

**Pull request merged**
